apiVersion: v1
kind: ConfigMap
metadata:
  name: static-cub
  namespace: prod-cybercom
data:
  default.conf: "server {\n    listen       80;\n    server_name  localhost;\n    resolver
    10.43.0.10;\n\n    location / {\n        root   /usr/local/openresty/nginx/html/;\n
    \       autoindex on;\n        auth_request /user;\n        #auth_request_set
    $auth_status $upstream_status;\n    }\n    \n    location = /user {\n        internal;\n
    \       set $upstream_user https://libapps.colorado.edu/api/user/;\n        proxy_pass
    $upstream_user;\n\n        proxy_pass_request_body off;\n        proxy_set_header
    Content-Length \"\";\n        proxy_set_header X-Original-URI $request_uri;\n
    \       proxy_set_header X-Original-METHOD $request_method;\n    }\n\n    error_page
    401 = @error401;\n    location @error401 { \n        set_escape_uri $request_uri_encoded
    $request_uri;\n        set $saml_sso https://libapps.colorado.edu/api/api-saml/sso/saml;\n
    \       return 302 $saml_sso?next=$request_uri_encoded;\n        #$request_uri;\n
    \   }\n    # redirect server error pages to the static page /50x.html\n    error_page
    \  500 502 503 504  /50x.html;\n    location = /50x.html {\n        root   /usr/share/nginx/html;\n
    \   }\n\n}"
