apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static
  name: static
  namespace: cybercom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - image: culibraries/static-cub:0.0.1
        imagePullPolicy: IfNotPresent
        name: static
        ports:
        - containerPort: 80
          name: 80tcp2
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/openresty/nginx/html/static
          name: static-secure
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginxvolume
          subPath: default.conf
      restartPolicy: Always
      securityContext: {}
      volumes:
      - name: static-secure
        nfs:
          path: /static_secure
          server: fs-981ef332.efs.us-west-2.amazonaws.com
      - configMap:
          defaultMode: 420
          name: static-cub
        name: nginxvolume

  